site_name: Cuckoo 3 docs
site_url: https://cuckoo-hatch.cert.ee/static/docs/
theme:
  name: readthedocs
  highlightjs: true
markdown_extensions:
- admonition
- attr_list

plugins:
- include-markdown

docs_dir: src
nav:
- Introduction:
  - Cuckoo 3: introduction/cuckoo.md
  - Sandboxing: introduction/sandboxing.md

- Installation:
  - Cuckoo 3 installation: installation/cuckoo.md
  - System dependencies: installation/deps.md
  - Machinery modules: installation/machineries.md
  - VM Creation: installation/vmcreation.md
  - Network routing: installation/routing.md

- Configuration:
  - System settings: configuration/system.md
  - Cuckoo 3 configuration:
    - Cuckoo.yaml: configuration/cuckooconfs/cuckooyaml.md
    - Distributed.yaml: configuration/cuckooconfs/distributedyaml.md
    - Web configuration:
      - Web.yaml: configuration/cuckooconfs/webconfs/webyaml.md
    - Node configuration:
      - Routing.yaml: configuration/cuckooconfs/nodeconfs/routingyaml.md


- Usage:
  - Submission: usage/submission/index.md
  - Web API:
    - Setup: usage/webapi/setup.md
    - Endpoints: usage/webapi/endpoints.md
  - Web UI: usage/webui/setup.md
  - Commands: usage/commands.md

- Development:
  - Overview: development/overview.md
  - Creating new machinery modules: development/creating_machinery.md

